/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.File;


import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void testQuoteFunction() {
        Quote[] quotes;

        quotes = App.quoteFunction();

        assertTrue(quotes.length > 0);
    }

    @Test
    public void testIfFileFound() {
        File findPath = new File("src/main/resources/recentquotes.json");

        boolean fileIfFound = findPath.exists();

        assertTrue(fileIfFound);
    }


}
